// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package appdb

import (
	"database/sql"
)

type Capability struct {
	Name        string
	Description string
}

type Credential struct {
	Login        string
	Encryption   string
	Password     string
	CreatedOn    sql.NullString
	LastModified sql.NullString
	MsAccountID  sql.NullString
}

type DatasetSharing struct {
	Ref              string
	CreatorUserLogin string
	CreationDate     string
	Name             string
	Details          sql.NullString
}

type DatasetSharingUser struct {
	DatasetRef          string
	DatasetCreatorLogin string
	UserLogin           string
	Mode                string
}

type Lang struct {
	Ref  string
	Name string
}

type MsAccountRequest struct {
	MsAccountID   string
	Email         string
	FullName      string
	RequestedDate string
	ProcessedDate sql.NullString
	ProcessedBy   sql.NullString
	Status        string
	LinkedLogin   sql.NullString
}

type Panel struct {
	ID   int64
	Name string
}

type Session struct {
	Token      string
	Login      string
	ExpiryDate string
}

type UserCapability struct {
	UserLogin      string
	CapabilityName string
	GrantedDate    string
	GrantedBy      string
}

type UserConfiguration struct {
	Login            string
	PrivateDirectory string
}

type UserHiddenPanel struct {
	UserLogin string
	PanelID   int64
}

type UserSelectedLang struct {
	UserLogin string
	LangRef   string
}
