// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package appdb

import (
	"database/sql"
)

type Credential struct {
	Login        string
	Encryption   string
	Password     string
	CreatedOn    sql.NullString
	LastModified sql.NullString
}

type DatasetSharing struct {
	Ref              string
	CreatorUserLogin string
	CreationDate     string
	Name             string
	Details          sql.NullString
}

type DatasetSharingUser struct {
	DatasetRef          string
	DatasetCreatorLogin string
	UserLogin           string
	Mode                string
}

type Lang struct {
	Ref  string
	Name string
}

type Panel struct {
	ID   int64
	Name string
}

type Session struct {
	Token      string
	Login      string
	ExpiryDate string
}

type UserConfiguration struct {
	Login            string
	PrivateDirectory string
}

type UserHiddenPanel struct {
	UserLogin string
	PanelID   int64
}

type UserSelectedLang struct {
	UserLogin string
	LangRef   string
}
