// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package storage

import (
	"database/sql"
)

type Book struct {
	DocumentRef string
	Isbn        sql.NullString
}

type CategoricalCharacter struct {
	DocumentRef string
	Color       sql.NullString
}

type DescriptorVisibilityInapplicable struct {
	DescriptorRef             string
	InapplicableDescriptorRef string
}

type DescriptorVisibilityRequirement struct {
	DescriptorRef         string
	RequiredDescriptorRef string
}

type Document struct {
	Ref      string
	Path     string
	DocOrder int32
	Name     string
	Details  string
}

type DocumentAttachment struct {
	Ref         string
	DocumentRef string
	Source      string
	Path        string
}

type DocumentTranslation struct {
	DocumentRef string
	LangRef     string
	Name        string
	Details     sql.NullString
}

type Lang struct {
	Ref  string
	Name string
}

type MesurementCharacter struct {
	DocumentRef string
	Color       sql.NullString
	UnitRef     sql.NullString
}

type State struct {
	DocumentRef string
	Color       sql.NullString
}

type Taxon struct {
	DocumentRef      string
	Author           string
	Website          sql.NullString
	Meaning          sql.NullString
	HerbariumNo      sql.NullInt32
	HerbariumPicture sql.NullString
	Fasc             sql.NullInt32
	Page             sql.NullInt32
}

type TaxonBookInfo struct {
	TaxonRef string
	BookRef  string
	Fasc     sql.NullInt32
	Page     sql.NullInt32
	Details  string
}

type TaxonDescription struct {
	TaxonRef       string
	DescriptionRef string
}

type TaxonMeasurement struct {
	TaxonRef     string
	CharacterRef string
	Minimum      sql.NullFloat64
	Maximum      sql.NullFloat64
}

type TaxonSpecimenLocation struct {
	TaxonRef      string
	SpecimenIndex int32
	Latitude      float64
	Longitude     float64
}

type Unit struct {
	Ref              string
	BaseUnitRef      sql.NullString
	ToBaseUnitFactor sql.NullFloat64
}
