// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package commonstorage

import (
	"database/sql"
)

type Credential struct {
	Login        string
	Encryption   sql.NullString
	Salt         sql.NullString
	Password     sql.NullString
	CreatedOn    sql.NullString
	LastModified sql.NullString
}
