// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package commonstorage

import (
	"database/sql"
)

type Credential struct {
	Login        string
	Encryption   string
	Password     string
	CreatedOn    sql.NullString
	LastModified sql.NullString
}

type Session struct {
	Token      string
	Login      string
	ExpiryDate string
}

type UserConfiguration struct {
	Login            string
	PrivateDirectory string
}
